version: 2
updates:
  - package-ecosystem: pnpm
    directory: /
    versioning-strategy: increase
    schedule:
      interval: weekly
  - package-ecosystem: pnpm
    directory: /frontend
    versioning-strategy: increase
    schedule:
      interval: weekly
  - package-ecosystem: pnpm
    directory: /backend
    versioning-strategy: increase
    schedule:
      interval: weekly
